HotelFlight/HotelFlight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('', include('login.urls')),
    path('', include('booking.urls')),
    path('', include('adminpanel.urls')),
    path('', include('siteadmin.urls'))
]

HotelFlight/adminpanel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('adminHotelDash', views.hoteladmindash, name='hotelAdminDash'),
    path('adminHotelUpdate', views.hoteladminupdate, name='hotelAdminUpdate'),
    path('adminHotelRooms', views.hoteladminrooms, name='hotelAdminRooms'),
    path('adminHotelRoomSingle', views.hoteladminroomsingle, name='hotelAdminRoomSingle'),
    path('adminHotelAddRoom', views.hoteladminaddroom, name='hotelAdminAddRoom'),
    path('adminHotelBookings', views.hoteladminbookings, name='hotelAdminBookings'),
    path('adminHotelCalender', views.hoteladmincalender, name='hotelAdminCalender'),
    path('adminHotelNotifications', views.hoteladminnotifications, name='hotelAdminNotifications'),
    path('adminHotelBookingsToday', views.hoteladminbookingstoday, name='hotelAdminBookingsToday'),
    path('adminHotelBookingConfirm', views.hoteladminbookingconfirm, name='hotelAdminBookingConfirm'),
    path('adminHotelBookingCancel', views.hoteladminbookingcancel, name='hotelAdminBookingCancel'),
    path('adminAirlinesDash', views.airlinesadmindash, name='airlinesAdminDash'),
    path('adminAirlinesAddRoute', views.airlinesadminaddroute, name='airlinesAdminAddRoute'),
    path('adminAirlinesAddFlightRoute', views.airlinesadminaddflightroute, name='airlinesAdminAddFlightRoute'),
    path('adminAirlinesViewFlights', views.airlinesadminflights, name='airlinesAdminViewFlights'),
    path('adminAirlinesUpdateFlights', views.airlinesadminflightsingle, name='airlinesAdminFlightSingle'),
    path('adminAirlinesAddFlight', views.airlinesadminaddflight, name='airlinesAdminAddFlight'),
    path('airlinesAdminCalendar', views.airlinesadmincalendar, name='airlinesAdminCalendar'),
    path('airlinesAdminBookings', views.airlinesadminbookings, name='airlinesAdminBookings'),
    path('adminAirlinesBookingsToday', views.airlinesAdminBookingsToday, name='airlinesAdminBookingsToday'),
    path('adminAirlinesBookingConfirm', views.airlinesadminbookingconfirm, name='airlinesAdminBookingConfirm'),
    path('adminAirlinesBookingCancel', views.airlinesadminbookingcancel, name='airlinesAdminBookingCancel'),
    path('adminAirlinesNotifications', views.airlinesadminnotifications, name='airlinesAdminNotifications')
]

HotelFlight/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('reg/', views.reg, name='reg'),
    path('logout/', views.logoutUser, name='logout'),
    path('userbookings', views.userbookings, name='userBookings'),
    path('userflightbookings', views.userflightbookings, name='userFlightBookings'),
    path('usernotifications', views.usernotifications, name='userNotifications'),
    path('userbookingcancel', views.bookingcancel, name='userBookingCancel'),
    path('userflightbookingcancel', views.flightbookingcancel, name='userFlightBookingCancel'),
    path('bookingcancelredirect', views.bookingcancelredirect, name='bookingCancelRedirect'),
    path('flightbookingcancelredirect', views.flightbookingcancelredirect, name='flightBookingCancelRedirect'),
    path('profile', views.userprofile, name='profile'),
    path('password', views.userpassword, name='password'),
]

HotelFlight/adminpanel/models.py
from django.db import models


# Create your models here.

def user_directory_path(instance, filename):
    return 'user_{0}/room_{1}/{2}'.format(instance.userid, instance.roomid, filename)


class Photos(models.Model):
    file = models.FileField(upload_to=user_directory_path)
    roomid = models.IntegerField()
    userid = models.IntegerField()

HotelFlight/database/models.py
import re
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    Phone = models.PositiveIntegerField()
    Address = models.CharField(max_length=1000)
    Passport_Number = models.CharField(max_length=100, null=True)
    Payment_Info = models.CharField(max_length=100, null=True)
    TotalSentMoney = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username


class Hotel(models.Model):
    Hotel_Name = models.CharField(max_length=200)
    Hotel_Location = models.CharField(max_length=500)
    Hotel_Country = models.CharField(max_length=500, null=True)
    TotalSentMoney = models.FloatField()
    Percentage = models.FloatField()
    CompanyAdmin = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Description = models.TextField(null=True)
    Address = models.CharField(max_length=200, null=True)
    Phone = models.PositiveIntegerField(null=True)
    Latitude = models.FloatField(null=True)
    Longitude = models.FloatField(null=True)

    def __str__(self):
        return self.Hotel_Name


class Room(models.Model):
    SingleBedCount = models.IntegerField()
    DoubleBedCount = models.IntegerField()
    RoomType = models.CharField(max_length=100)
    AirConditioner = models.BooleanField()

    def __str__(self):
        return 'Type:' + self.RoomType + '   Single Bed:' + str(self.SingleBedCount) + '   Double Bed:' + str(
            self.DoubleBedCount) + '   AC:' + str(self.AirConditioner)


class Cancellation_Policy(models.Model):
    DaysCount = models.IntegerField(default=10)
    Percentage_refunding = models.FloatField(default=80.0)


class Hotel_Room(models.Model):
    Hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    Room = models.ForeignKey(Room, on_delete=models.CASCADE)
    Price = models.FloatField()
    Complimentary_Breakfast = models.BooleanField()
    Wifi = models.BooleanField()
    TotalRoomCount = models.IntegerField(default=2)
    FreeRoomCount = models.IntegerField(default=2)
    Cancellation_Policy = models.ForeignKey(Cancellation_Policy, on_delete=models.CASCADE, default=1)


class Air_Company(models.Model):
    AirCompany_Name = models.CharField(max_length=200)
    TotalSentMoney = models.FloatField()
    Percentage = models.FloatField()
    CompanyAdmin = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.AirCompany_Name


class Flight(models.Model):
    AirCompany = models.ForeignKey(Air_Company, on_delete=models.CASCADE)
    Airplane_Number = models.CharField(max_length=200)
    Aircraft = models.CharField(max_length=200, null=True)
    TotalSeats = models.PositiveIntegerField(default=100, null=True)

    def __str__(self):
        return self.Airplane_Number


class Route(models.Model):
    Source = models.CharField(max_length=200)
    Destination = models.CharField(max_length=200)

    def __str__(self):
        return self.Source + " - " + self.Destination


class Flight_Route(models.Model):
    Route = models.ForeignKey(Route, on_delete=models.CASCADE)
    Flight = models.ForeignKey(Flight, on_delete=models.CASCADE)
    Time = models.TimeField(auto_now=False, auto_now_add=False, null=True)
    Date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    Price = models.FloatField(null=True)
    Duration = models.IntegerField(default=30, null=True)
    Source_Airport = models.CharField(max_length=200, null=True)
    Destination_Airport = models.CharField(max_length=200, null=True)
    TotalSeatsBooked = models.PositiveIntegerField(default=0, null=True)
    Cancellation_Policy = models.ForeignKey(Cancellation_Policy, on_delete=models.CASCADE, default=1)


class Booking(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    MoneyToPay = models.FloatField()
    MoneyToRefund = models.FloatField()
    DateOfBooking = models.DateField(auto_now=False, auto_now_add=False)
    DateOfCancellation = models.DateField(auto_now=False, auto_now_add=False)
    isCancelled = models.BooleanField(default=False)
    # 0 Booked, 1 Confirmed, 2 Cancelled
    Status = models.IntegerField(default=0)
    PaidMoney = models.FloatField(default=0)

    def __str__(self):
        return self.User + ' ' + self.DateOfBooking


class Hotel_Booking(models.Model):
    Booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    Hotel_Room = models.ForeignKey(Hotel_Room, on_delete=models.CASCADE)
    Checkin_Date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    Checkout_Date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    TotalRooms = models.PositiveIntegerField(default=1, null=True)
    isApproved = models.BooleanField(null=True, default=False)
    isCancellationApproved = models.BooleanField(null=True, default=False)


class Flight_Booking(models.Model):
    Booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    Flight = models.ForeignKey(Flight_Route, on_delete=models.CASCADE, null=True)
    TotalSeats = models.PositiveIntegerField(default=1, null=True)
    isApproved = models.BooleanField(null=True, default=False)
    isCancellationApproved = models.BooleanField(null=True, default=False)


class Payment_Log(models.Model):
    Admin = models.ForeignKey(User, on_delete=models.CASCADE)
    Booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    Timestamp = models.DateTimeField(default=datetime.now, blank=True)
    # True for credit(money goes from user to hotel/airlines),False for debit (money goes from hotel/airlines to user)
    Flag = models.BooleanField(null=True, default=True)


class Cancellation_Log(models.Model):
    Admin = models.ForeignKey(User, on_delete=models.CASCADE)
    Booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    notified = models.BooleanField(default=False)


class BookingLog(models.Model):
    Admin = models.ForeignKey(User, on_delete=models.CASCADE)
    Booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    # 0 admin, 1 user
    Actor = models.BooleanField(default=False)
    Message = models.CharField(max_length=100, null=True)
    notified = models.BooleanField(default=False)

HotelFlight/adminpanel/forms.py
from database.models import *
from .models import Photos
from django import forms
from django.forms import ClearableFileInput
from collections import namedtuple
from django.db import connection


def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]


CHOICES = (
    ('True', 'Yes'),
    ('False', 'No'),
)

ROOMTYPES = (
    ('1', 'Deluxe  SingleBed:0  DoubleBed:1 AC'),
    ('2', 'Casual  SingleBed:2  DoubleBed:0 AC'),
    ('3', 'Casual  SingleBed:1  DoubleBed:0 Non-AC'),
    ('4', 'Suite   SingleBed:0  DoubleBed:2 AC'),
    ('5', 'Suite   SingleBed:1  DoubleBed:2 AC')

)


class hotelupdateform(forms.Form):
    name = forms.CharField(max_length=200)
    location = forms.CharField(max_length=500)
    country = forms.CharField(max_length=500)
    description = forms.Textarea()
    address = forms.CharField(max_length=200)
    phone = forms.IntegerField()


class photoupload(forms.ModelForm):
    class Meta:
        model = Photos
        fields = ('file', 'roomid', 'userid')
        widgets = {
            'file': ClearableFileInput(attrs={'multiple': True}),
        }


class HotelUpdateRoom(forms.Form):
    wifi = forms.ChoiceField(choices=CHOICES)
    breakfast = forms.ChoiceField(choices=CHOICES)
    price = forms.IntegerField()
    roomCount = forms.IntegerField()


class HotelAddRoomForm(forms.Form):
    room = forms.ChoiceField(choices=ROOMTYPES)
    wifi = forms.ChoiceField(choices=CHOICES)
    breakfast = forms.ChoiceField(choices=CHOICES)
    price = forms.DecimalField()
    roomCount = forms.IntegerField()


class FlightAddRouteForm(forms.Form):
    Source = forms.CharField(max_length=200)
    Destination = forms.CharField(max_length=200)


class airlinesupdateform(forms.Form):
    name = forms.CharField(max_length=200)
    # address = forms.CharField(max_length=200)
    # phone = forms.IntegerField()


class FlightUpdateForm(forms.Form):
    TotalSeats = forms.IntegerField()


class FlightAddFlight(forms.Form):
    AirplaneNumber = forms.CharField(max_length=200)
    Aircraft = forms.CharField(max_length=200)
    TotalSeats = forms.IntegerField()


class FlightAddFlightRoute(forms.Form):
    my_arg = 0

    def __init__(self, *args, **kwargs):
        my_arg = kwargs.pop('my_arg')
        super(FlightAddFlightRoute, self).__init__(*args, **kwargs)
        self.my_arg = my_arg
        print("my_Arg")
        print(my_arg)
        cursor = connection.cursor()
        cursor.execute("SELECT F.id,F.Airplane_Number, F.Aircraft,F.TotalSeats "
                       "FROM database_flight F JOIN database_air_company A on (A.id = F.AirCompany_id) "
                       "WHERE A.CompanyAdmin_id = %s", [my_arg])
        my_tuple2 = []
        results = cursor.fetchall()
        for row in results:
            str = row[1]
            my_tuple2.append((row[0], str))

        FLIGHTS = tuple(my_tuple2)
        self.fields['Flight'] = forms.ChoiceField(choices=FLIGHTS)

    # my_field = forms.CharField(initial=my_arg)
    results = Route.objects.all()
    my_tuple = []
    i = 1
    for row in results:
        var = row.Source + "-" + row.Destination
        my_tuple.append((i, var))
        i = i + 1
    ROUTES = tuple(my_tuple)

    results = Cancellation_Policy.objects.all()
    my_tuple = []
    i = 1
    for row in results:
        var = []
        var.append('Booking can be cancelled upto ')
        var.append(str(row.DaysCount))
        var.append(' days of booking and ')
        var.append(str(row.Percentage_refunding))
        var.append('% of advanced payment is returned to the customer')
        var = ''.join(var)

        # var =  "Booking can be cancelled upto " #+ ' days of booking and ' + str(row.Percentage_refunding) + '% of advanced payment is returned to the customer'
        my_tuple.append((i, var))
        i = i + 1
    CANCELLATIONPOLICIES = tuple(my_tuple)

    Route = forms.ChoiceField(choices=ROUTES)
    Cancellation_Policy = forms.ChoiceField(choices=CANCELLATIONPOLICIES)
    Source_Airport = forms.CharField(max_length=200)
    Destination_Airport = forms.CharField(max_length=200)
    Date = forms.DateField()
    Time = forms.TimeField()
    Duration = forms.IntegerField()
    Price = forms.IntegerField()

HotelFlight/HotelFlight/templates/adminpanel/airlinesAdminAddFlightRoute.html
{% extends "search/base.html" %}

{% load static %}
{% load url_replace %}
{% load url_get %}
{% load widget_tweaks %}


{% block title %}Add Route | {{ request.user }}{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/bootstrap4/bootstrap.min.css' %}">
    <link href="{% static 'search/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/search.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/single_listing_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'gijgo/js/gijgo.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminpanel/sidebar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" >

{% endblock css %}

{% block content %}

    <div class="offers">

        <div class="hero-image"
             style="height:24.5%;background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({% static 'search/images/single_background.jpg' %})">
        </div>

        <!-- Sidebar -->
        <div class="">
            <div class="row">
                <div class="col-lg-2" style="display: flex">
                    <nav id="sidebar">
                        <div class="sidebar-header">
                            <h3>Options</h3>
                        </div>
                        <ul class="list-unstyled components">
                            <p>Add flight to a Route</p>
                            <li class="">
                                <a href="{% url 'airlinesAdminDash' %}">Dashboard</a>
                            </li>
                            <li class="notification">
                                <a href="{% url 'airlinesAdminNotifications' %}">
                                    Notifications
                                    {% if countN > 0 %}
                                        <span class="badge">{{ countN }}</span>
                                    {% endif %}
                                </a>
                            </li>
                             <li>
                                <a href="{% url 'airlinesAdminAddRoute' %}">Add Route</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminAddFlight' %}">Add Flight</a>
                            </li>
                            <li class="active">
                                <a href="{% url 'airlinesAdminAddFlightRoute' %}">Add Flight to a route</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminViewFlights' %}">View Flights</a>
                            </li>

                            <li class="">
                                <a href="{% url 'airlinesAdminBookings' %}">View Bookings</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminBookingsToday' %}">View Today's Bookings</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminCalendar' %}">Calendar</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-8">
                    <div class="contact_form_container text-center">
                        <div class="contact_title text-center">
                            Add New Flight To a Route
                        </div>
                        <div class="contact_title text-center">

                                    {% for message in messages %}
                                        <div {% if message.extra_tags %} class="alert {{ message.extra_tags }}"{% endif %}>
                                            <a class="close" href="" {% if message.extra_tags %} data-dismiss="{{ message.extra_tags }}"{% endif %}>×</a>
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                </div>
                        <form method="POST" id="contact_form" class="contact_form" enctype="multipart/form-data">


                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Route :</div>
                                        {% render_field addflightrouteform.Route class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Flight :</div>
                                        {% render_field addflightrouteform.Flight class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Source Airport :</div>
                                        {% render_field addflightrouteform.Source_Airport class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Destination Airport :</div>
                                        {% render_field addflightrouteform.Destination_Airport class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Date :</div>
                                        {% render_field addflightrouteform.Date class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Time :</div>
                                        {% render_field addflightrouteform.Time class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Duration(in minutes) :</div>
                                        {% render_field addflightrouteform.Duration class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Price :</div>
                                        {% render_field addflightrouteform.Price class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Cancellation Policy :</div>
                                        {% render_field addflightrouteform.Cancellation_Policy class="contact_form_email input_field" style="color:black;" %}
                                    </div>
                                </div>
                            </div>
                            <button type="submit" id="form_submit_button"
                                    class="form_submit_button button trans_200">Add Flight
                            </button>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block jscript %}
<script>
    var today = new Date().getFullYear() + "-" + (new Date().getMonth() + 1) + "-" + new Date().getDate()
    var tommorrow = new Date().getFullYear() + "-" + (new Date().getMonth() + 1) + "-" + (new Date().getDate()+1)
    $('#id_Date').datepicker({
        uiLibrary: 'bootstrap4',
        value: today,
        minDate: today,
        format: 'yyyy-mm-dd',
        size: 'small'
    });

    $('#id_Route').dropdown({
        uiLibrary: 'materialdesign'
    });
    $('#id_Flight').dropdown();
    $('#id_Cancellation_Policy').dropdown();
</script>
{% endblock jscript %}

HotelFlight/HotelFlight/templates/adminpanel/airlinesAdminAddRoute.html
{% extends "search/base.html" %}

{% load static %}
{% load url_replace %}
{% load url_get %}
{% load widget_tweaks %}


{% block title %}Add Route | {{ request.user }}{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/bootstrap4/bootstrap.min.css' %}">
    <link href="{% static 'search/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/search.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/single_listing_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'search/styles/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'gijgo/js/gijgo.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminpanel/sidebar.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

{% endblock css %}

{% block content %}

    <div class="offers">

        <div class="hero-image"
             style="height:24.5%;background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({% static 'search/images/single_background.jpg' %})">
        </div>

        <!-- Sidebar -->
        <div class="">
            <div class="row">
                <div class="col-lg-2" style="display: flex">
                    <nav id="sidebar">
                        <div class="sidebar-header">
                            <h3>Options</h3>
                        </div>
                        <ul class="list-unstyled components">
                            <p>Add Route</p>
                            <li class="">
                                <a href="{% url 'airlinesAdminDash' %}">Dashboard</a>
                            </li>
                            <li class="notification">
                                <a href="{% url 'airlinesAdminNotifications' %}">
                                    Notifications
                                    {% if countN > 0 %}
                                        <span class="badge">{{ countN }}</span>
                                    {% endif %}
                                </a>
                            </li>

                             <li class="active">
                                <a href="{% url 'airlinesAdminAddRoute' %}">Add Route</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminAddFlight' %}">Add Flight</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminAddFlightRoute' %}">Add Flight to a route</a>
                            </li>
                            <li>
                                <a href="{% url 'airlinesAdminViewFlights' %}">View Flights</a>
                            </li>

                            <li class="">
                                <a href="{% url 'airlinesAdminBookings' %}">View Bookings</a>
                            </li>
                            <li class="">
                                <a href="{% url 'airlinesAdminBookingsToday' %}">View Today's Bookings</a>
                            </li>

                            <li>
                                <a href="{% url 'airlinesAdminCalendar' %}">Calendar</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-8">
                    <div class="contact_form_container text-center">
                        <div class="contact_title text-center">
                            Add New Route
                        </div>
                        <div class="contact_title text-center">

                                    {% for message in messages %}
                                        <div {% if message.extra_tags %} class="alert {{ message.extra_tags }}"{% endif %}>
                                            <a class="close" href="" {% if message.extra_tags %} data-dismiss="{{ message.extra_tags }}"{% endif %}>×</a>
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                </div>
                        <form method="POST" id="contact_form" class="contact_form" enctype="multipart/form-data">


                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Source :</div>
                                        {% render_field addrouteform.Source class="contact_form_email input_field" %}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 25px;">
                                <div class="col-lg-12">
                                    <div class="contact_item">
                                        <div align="left">Destination :</div>
                                        {% render_field addrouteform.Destination class="contact_form_email input_field" %}
                                    </div>
                                </div>
                            </div>

                            <button type="submit" id="form_submit_button"
                                    class="form_submit_button button trans_200">Add Route
                            </button>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}